export function getUpcomingEvents(): Promise<any[]> {
  return new Promise((resolve, reject) => {
    resolve([
      {
        id: 0,
        title: "Event 1",
        description: "Will be about getting people together",
        event_start: "23/01/2019",
        event_end: "25/01/2019",
        belongs_to_hubs: [null],
        venue_name: "Sirikwa Hotel",
        address: "Oloo Street",
        city: "Eldoret",
        state: "Uasin Gishu",
        zip_code: "string",
        country: "Kenya",
        created_at: "string",
        fq_url: "string",
        paid_for_domain: true,
        domain: "string",
        custom_domain: "string",
        event_type: "string",
        splash_theme: {},
        ticket_types: [null],
        group_ids: [0]
      },
      {
        id: 0,
        title: "Event 1",
        description: "Will be about getting people together",
        event_start: "23/01/2019",
        event_end: "25/01/2019",
        belongs_to_hubs: [null],
        venue_name: "Sirikwa Hotel",
        address: "Oloo Street",
        city: "Eldoret",
        state: "Uasin Gishu",
        zip_code: "string",
        country: "Kenya",
        created_at: "string",
        fq_url: "string",
        paid_for_domain: true,
        domain: "string",
        custom_domain: "string",
        event_type: "string",
        splash_theme: {},
        ticket_types: [null],
        group_ids: [0]
      },
      {
        id: 0,
        title: "Event 1",
        description: "Will be about getting people together",
        event_start: "23/01/2019",
        event_end: "25/01/2019",
        belongs_to_hubs: [null],
        venue_name: "Sirikwa Hotel",
        address: "Oloo Street",
        city: "Eldoret",
        state: "Uasin Gishu",
        zip_code: "string",
        country: "Kenya",
        created_at: "string",
        fq_url: "string",
        paid_for_domain: true,
        domain: "string",
        custom_domain: "string",
        event_type: "string",
        splash_theme: {},
        ticket_types: [null],
        group_ids: [0]
      },
      {
        id: 0,
        title: "Event 1",
        description: "Will be about getting people together",
        event_start: "23/01/2019",
        event_end: "25/01/2019",
        belongs_to_hubs: [null],
        venue_name: "Sirikwa Hotel",
        address: "Oloo Street",
        city: "Eldoret",
        state: "Uasin Gishu",
        zip_code: "string",
        country: "Kenya",
        created_at: "string",
        fq_url: "string",
        paid_for_domain: true,
        domain: "string",
        custom_domain: "string",
        event_type: "string",
        splash_theme: {},
        ticket_types: [null],
        group_ids: [0]
      }
    ]);
  });
}
